server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/junit_test_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password:  
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
